In [1]:
#Import Pandas
import pandas as pd

In [2]:
#Read Dataset
df = pd.read_csv(
    'https://raw.githubusercontent.com/CunyLaguardiaDataAnalytics/datasets/master/mtcars.csv'
)

In [5]:
#Understand the Data First
# Rows
df.head()

,Unnamed: 0,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
0,Mazda RX4,21.0,6,160.0,110,3.90,2.620,16.46,0,1,4,4
1,Mazda RX4 Wag,21.0,6,160.0,110,3.90,2.875,17.02,0,1,4,4
2,Datsun 710,22.8,4,108.0,93,3.85,2.320,18.61,1,1,4,1
3,Hornet 4 Drive,21.4,6,258.0,110,3.08,3.215,19.44,1,0,3,1
4,Hornet Sportabout,18.7,8,360.0,175,3.15,3.440,17.02,0,0,3,2

In [8]:
# Understand the Data First
# Describe
df.describe()
#Result: 32 MPG observations, Mean (average)= 20.09

,mpg,cyl,disp,hp,drat,wt,qsec,vs,am,gear,carb
count,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.000000,32.0000
mean,20.090625,6.187500,230.721875,146.687500,3.596563,3.217250,17.848750,0.437500,0.406250,3.687500,2.8125
std,6.026948,1.785922,123.938694,68.562868,0.534679,0.978457,1.786943,0.504016,0.498991,0.737804,1.6152
min,10.400000,4.000000,71.100000,52.000000,2.760000,1.513000,14.500000,0.000000,0.000000,3.000000,1.0000
25%,15.425000,4.000000,120.825000,96.500000,3.080000,2.581250,16.892500,0.000000,0.000000,3.000000,2.0000
50%,19.200000,6.000000,196.300000,123.000000,3.695000,3.325000,17.710000,0.000000,0.000000,4.000000,2.0000
75%,22.800000,8.000000,326.000000,180.000000,3.920000,3.610000,18.900000,1.000000,1.000000,4.000000,4.0000
max,33.900000,8.000000,472.000000,335.000000,4.930000,5.424000,22.900000,1.000000,1.000000,5.000000,8.0000

In [14]:
#Understand the Data First
#Columns
df.info()
#Result: 32 entries, 12 Columns, Column Names, Non-Null Counts, DataType

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 12 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  32 non-null     object
 1   mpg         32 non-null     float64
 2   cyl         32 non-null     int64
 3   disp        32 non-null     float64
 4   hp          32 non-null     int64
 5   drat        32 non-null     float64
 6   wt          32 non-null     float64
 7   qsec        32 non-null     float64
 8   vs          32 non-null     int64
 9   am          32 non-null     int64
 10  gear        32 non-null     int64
 11  carb        32 non-null     int64
dtypes: float64(5), int64(6), object(1)
memory usage: 3.1+ KB

In [18]:
#Clean the Data Set
#Rename the unnamed column
df.rename(columns={'Unnamed: 0': 'car'}, inplace=True)

In [46]:
#Create new data frame
#Result: Created new dataframe named df2 (from df)
#Result: Contains only 4 columns (mpg, hp, wt, cycle)
#Reads: df2 equals df, selecting only mpg, hp, wt, cycl
df2 = df[['mpg', 'hp', 'wt', 'cyl']]

In [47]:
# Rename the four columns
# Reads as: Rename mpg= miles per gallon, hp = horsepower, wt= weight, cyl = cylinders
df2 = df2.rename(columns={
    'mpg': 'miles_per_gallon',
    'hp': 'horsepower',
    'wt': 'weight',
    'cyl': 'cylinders'
})

In [48]:
#Summary Statistics for those columns
# Use Describe again
# Reads: Summary of only those 4 columns
# Result: Gives averages and counts of 4 columnns (variables)
df2.describe()

       miles_per_gallon  horsepower     weight  cylinders
count         32.000000   32.000000  32.000000  32.000000
mean          20.090625  146.687500   3.217250   6.187500
std            6.026948   68.562868   0.978457   1.785922
min           10.400000   52.000000   1.513000   4.000000
25%           15.425000   96.500000   2.581250   4.000000
50%           19.200000  123.000000   3.325000   6.000000
75%           22.800000  180.000000   3.610000   8.000000
max           33.900000  335.000000   5.424000   8.000000

In [49]:
#Read
df2.head()

   miles_per_gallon  horsepower  weight  cylinders
0              21.0         110   2.620          6
1              21.0         110   2.875          6
2              22.8          93   2.320          4
3              21.4         110   3.215          6
4              18.7         175   3.440          8

In [58]:
#Filter your Data plus Find Summary Statistics for Only One Type of Vehicle
#Create a new subset (create a new dataframe called four_cycl)
#Contains one type of vehicle =
#(Contains only the rows from df2 where the cylinders column equals 4)

four_cyl = df2[df2['cylinders'] == 4]

In [53]:
#Read
four_cyl.head()

    miles_per_gallon  horsepower  weight  cylinders
2               22.8          93   2.320          4
7               24.4          62   3.190          4
8               22.8          95   3.150          4
17              32.4          66   2.200          4
18              30.4          52   1.615          4

In [59]:
#Summary Statistics- Describe
four_cyl.describe()

       miles_per_gallon  horsepower     weight  cylinders
count         11.000000   11.000000  11.000000       11.0
mean          26.663636   82.636364   2.285727        4.0
std            4.509828   20.934530   0.569564        0.0
min           21.400000   52.000000   1.513000        4.0
25%           22.800000   65.500000   1.885000        4.0
50%           26.000000   91.000000   2.200000        4.0
75%           30.400000   96.000000   2.622500        4.0
max           33.900000  113.000000   3.190000        4.0